### ISSUE TITLE
Licensing and credits

### ISSUE THREAD

**Issue by tommywalkie** [deebloo/virtual-fs#9]
Hi @deebloo, I was looking for a virtual filesystem implementation for a Deno project [`gauntlet`](https://github.com/tommywalkie/gauntlet) and ran into your project.

Despite needing to vendor the module and add a couple of bindings for Deno (_i.e._ for `rxjs`), it works like a charm, thank you for making this project ❤️

I wanted to ask a few questions:
- Is the library hosted on NPM? (`package.json` mentions the package name is `virtual-fs` but it is already taken, also there are few mentions about [`drill`](https://github.com/deebloo/drill) but I guess these are just typos)
- Repo has no LICENSE file but `package.json` mentions MIT License, is it still accurate ?
- Author field in `package.json` is empty, is it possible to update it ?

Thank you.

**Comment by deebloo** [comment]
oh hey thanks! I haven't thought about this for a while. I can't remember if it is hosted on npm or not but I can certainly make it so and update it. Also I am not using it for anything so we can make changes to make it more deno friendly if you like

**Comment by deebloo** [comment]
https://www.npmjs.com/package/memfs is the standard but I know it is very focused on thee node api

**Comment by deebloo** [comment]
@tommywalkie I updated and published to npm under "simple-virtual-fs".

**Comment by tommywalkie** [comment]
Wow first of all, thanks @deebloo for the quick response and the newly published package!

> we can make changes to make it deno friendly if you like

Some CDNs already take care of rewriting imports so [it already _just works_](https://codepen.io/tommywalkie/pen/NWdELEe). Before the package was published, I could already [implement a few more methods like `lstat`, `exists` and `walk`](https://github.com/tommywalkie/gauntlet/blob/68694296a3bed47f833e74a8438d7d873662d79b/src/core/fs.test.ts), which _could be_ new PR ideas😄 

That said, the TypeScript experience could be better, the `VirtualFs` class lost its generic type `<T>` upon the package release.

**Comment by tommywalkie** [comment]
> That said, the TypeScript experience could be better, the `VirtualFs` class lost its generic type `<T>` upon the package release.

Erratum, forgot the `?dts` query parameter in the URL, though it still couldn't fix the issue cause Skypack doesn't know where are the typings file (`/target/lib.d.ts`), just need to add a `types` property on `package.json` I guess

**Comment by deebloo** [comment]
Ah ok. If you open a PR adding the typings I'll merge and release. And yeah! It would be cool to add more methods.

**Comment by tommywalkie** [comment]
Guess the hereby issue was solved since https://github.com/deebloo/virtual-fs/commit/a3fef38c887dddaf64f89cebf9e10f43ed23a558 so we can close it and move unrelated discussion and PR ideas to new threads.
